# User configuration

export GIT_EDITOR=nvim

function fish_prompt
    # Цвета:
    set_color -o blue    # user
    echo -n (whoami)

    set_color normal
    echo -n "@"

    set_color green      # hostname
    echo -n (hostname)

    set_color normal
    echo -n " "

    set_color yellow     # путь
    echo -n (prompt_pwd)

    set_color normal
    echo -n " "

    set_color magenta    # git ветка
    echo -n (fish_vcs_prompt)

    echo
    set_color brwhite
    echo -n "> "
    set_color normal
end

fish_add_path /home/ioannco/cli-tools/bin

# Machine-specific config (generated by dotfiles installer, not tracked)
test -f ~/.config/fish/local.fish; and source ~/.config/fish/local.fish
